//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sonic3AIR_ModManager.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class lang_fr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang_fr() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sonic3AIR_ModManager.Languages.lang_fr", typeof(lang_fr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En savoir plus....
        /// </summary>
        internal static string AboutTab {
            get {
                return ResourceManager.GetString("AboutTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter un Mod....
        /// </summary>
        internal static string AddAMod {
            get {
                return ResourceManager.GetString("AddAMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrez le nom de la manette telle qu&apos;il apparaît dans les paramètres système ou tapez * pour cibler tous les périphériques..
        /// </summary>
        internal static string AddNewDeviceDescription {
            get {
                return ResourceManager.GetString("AddNewDeviceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter un nouveau périphérique....
        /// </summary>
        internal static string AddNewDeviceTitle {
            get {
                return ResourceManager.GetString("AddNewDeviceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emplacement non défini. Impossible de démarrer Sonic 3 A.I.R !.
        /// </summary>
        internal static string AIRCanNotStartNoPath {
            get {
                return ResourceManager.GetString("AIRCanNotStartNoPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les paramètres définis par le fichier n’existent plus. Relancez AIR en dehors du mod loader puis réessayez..
        /// </summary>
        internal static string AIRChangePathNoLongerExists {
            get {
                return ResourceManager.GetString("AIRChangePathNoLongerExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activer le mode dev (pas le Debug Mode).
        /// </summary>
        internal static string AIRDevMode {
            get {
                return ResourceManager.GetString("AIRDevMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paramètre interne de A.I.R.
        /// </summary>
        internal static string AIRInternalSettings {
            get {
                return ResourceManager.GetString("AIRInternalSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Média A.I.R....
        /// </summary>
        internal static string AIRMedia {
            get {
                return ResourceManager.GetString("AIRMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emplacement de A.I.R Mod Manager ....
        /// </summary>
        internal static string AIRMMPlaces {
            get {
                return ResourceManager.GetString("AIRMMPlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emplacement de A.I.R....
        /// </summary>
        internal static string AIRPlaces {
            get {
                return ResourceManager.GetString("AIRPlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version A.I.R.
        /// </summary>
        internal static string AIRVersion {
            get {
                return ResourceManager.GetString("AIRVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La version de A.I.R..
        /// </summary>
        internal static string AIRVersionColumnHeader {
            get {
                return ResourceManager.GetString("AIRVersionColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recherche de mises à jour....
        /// </summary>
        internal static string AutoBoot_CheckingForUpdates {
            get {
                return ResourceManager.GetString("AutoBoot_CheckingForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialisation....
        /// </summary>
        internal static string AutoBoot_Initalizing {
            get {
                return ResourceManager.GetString("AutoBoot_Initalizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lancer en.
        /// </summary>
        internal static string AutoBoot_LaunchingIn {
            get {
                return ResourceManager.GetString("AutoBoot_LaunchingIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Délai (secondes):.
        /// </summary>
        internal static string AutoBootDelay {
            get {
                return ResourceManager.GetString("AutoBootDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axe/POV.
        /// </summary>
        internal static string AxisPOVLabel {
            get {
                return ResourceManager.GetString("AxisPOVLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axe.
        /// </summary>
        internal static string AxisRadioButton {
            get {
                return ResourceManager.GetString("AxisRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bouton :.
        /// </summary>
        internal static string ButtonLabel {
            get {
                return ResourceManager.GetString("ButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réglages des boutons.
        /// </summary>
        internal static string ButtonMappings {
            get {
                return ResourceManager.GetString("ButtonMappings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.
        /// </summary>
        internal static string Buttons_A {
            get {
                return ResourceManager.GetString("Buttons_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        internal static string Buttons_B {
            get {
                return ResourceManager.GetString("Buttons_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Buttons_Back {
            get {
                return ResourceManager.GetString("Buttons_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bas.
        /// </summary>
        internal static string Buttons_Down {
            get {
                return ResourceManager.GetString("Buttons_Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gauche.
        /// </summary>
        internal static string Buttons_Left {
            get {
                return ResourceManager.GetString("Buttons_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Droite.
        /// </summary>
        internal static string Buttons_Right {
            get {
                return ResourceManager.GetString("Buttons_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Buttons_Start {
            get {
                return ResourceManager.GetString("Buttons_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haut.
        /// </summary>
        internal static string Buttons_Up {
            get {
                return ResourceManager.GetString("Buttons_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        internal static string Buttons_X {
            get {
                return ResourceManager.GetString("Buttons_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y.
        /// </summary>
        internal static string Buttons_Y {
            get {
                return ResourceManager.GetString("Buttons_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Par.
        /// </summary>
        internal static string By {
            get {
                return ResourceManager.GetString("By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuler.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Annuler.
        /// </summary>
        internal static string Cancel_Button {
            get {
                return ResourceManager.GetString("Cancel_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CarJem @ Twitter.
        /// </summary>
        internal static string CarJemTwitter {
            get {
                return ResourceManager.GetString("CarJemTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vérifier les mises à jour de A.I.R au démarrage .
        /// </summary>
        internal static string CheckforAIRUpdatesOnStart {
            get {
                return ResourceManager.GetString("CheckforAIRUpdatesOnStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vérifier les mises à jour de A.I.R....
        /// </summary>
        internal static string CheckForGameUpdatesExpandable {
            get {
                return ResourceManager.GetString("CheckForGameUpdatesExpandable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vérifier les mises à jour du Mod Manager.
        /// </summary>
        internal static string CheckForModManagerUpdatesButton {
            get {
                return ResourceManager.GetString("CheckForModManagerUpdatesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les fichiers suivants sont introuvables :.
        /// </summary>
        internal static string CollectionFilesCouldNotBeFound1 {
            get {
                return ResourceManager.GetString("CollectionFilesCouldNotBeFound1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si vous n&apos;avez pas encore exécuté Sonic 3 A.I.R, veuillez lancer Sonic 3 A.I.R avant d&apos;exécuter le Mod Loader !.
        /// </summary>
        internal static string CollectionFilesCouldNotBeFound2 {
            get {
                return ResourceManager.GetString("CollectionFilesCouldNotBeFound2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si vous les avez, assurez-vous que ces emplacements existent. Le Mod Loader ne peut pas fonctionner sans eux.
        /// </summary>
        internal static string CollectionFilesCouldNotBeFound3 {
            get {
                return ResourceManager.GetString("CollectionFilesCouldNotBeFound3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manette.
        /// </summary>
        internal static string ControllerRadioButton {
            get {
                return ResourceManager.GetString("ControllerRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copier l&apos;emplacement du fichier.
        /// </summary>
        internal static string CopyFilePath {
            get {
                return ResourceManager.GetString("CopyFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personnalisé/Avancé :.
        /// </summary>
        internal static string CustomAdvancedLabel {
            get {
                return ResourceManager.GetString("CustomAdvancedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chaîne personnalisée :.
        /// </summary>
        internal static string CustomStringLabel {
            get {
                return ResourceManager.GetString("CustomStringLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diminuer la priorité du mod sélectionné....
        /// </summary>
        internal static string DecreaseModPriority {
            get {
                return ResourceManager.GetString("DecreaseModPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diminuer la priorité du mod sélectionné sur Min....
        /// </summary>
        internal static string DecreaseModPriorityToMin {
            get {
                return ResourceManager.GetString("DecreaseModPriorityToMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supprimer.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supprimer un périphérique.
        /// </summary>
        internal static string DeleteDeviceTitle {
            get {
                return ResourceManager.GetString("DeleteDeviceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etes-vous sûr de vouloir supprimer.
        /// </summary>
        internal static string DeleteItemConfirmation {
            get {
                return ResourceManager.GetString("DeleteItemConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supprimer le raccourci clavier.
        /// </summary>
        internal static string DeleteKeybindTitle {
            get {
                return ResourceManager.GetString("DeleteKeybindTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vérification : voulez-vous supprimer le.
        /// </summary>
        internal static string DeleteKeybindVerification1 {
            get {
                return ResourceManager.GetString("DeleteKeybindVerification1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to raccourci clavier ?.
        /// </summary>
        internal static string DeleteKeybindVerification2 {
            get {
                return ResourceManager.GetString("DeleteKeybindVerification2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Détecter la manette....
        /// </summary>
        internal static string DetectControllerExpandable {
            get {
                return ResourceManager.GetString("DetectControllerExpandable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Détecter l&apos;input de la manette....
        /// </summary>
        internal static string DetectGamepadInputExpandable {
            get {
                return ResourceManager.GetString("DetectGamepadInputExpandable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noms d&apos;identifiant de périphérique.
        /// </summary>
        internal static string DeviceIdentifierNames {
            get {
                return ResourceManager.GetString("DeviceIdentifierNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direction.
        /// </summary>
        internal static string DirectionGB {
            get {
                return ResourceManager.GetString("DirectionGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Téléchargement.
        /// </summary>
        internal static string Downloading {
            get {
                return ResourceManager.GetString("Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier....
        /// </summary>
        internal static string EditExpandable {
            get {
                return ResourceManager.GetString("EditExpandable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier les raccourcis clavier....
        /// </summary>
        internal static string EditKeybindingsTitleExpandable {
            get {
                return ResourceManager.GetString("EditKeybindingsTitleExpandable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activer le mode de démarrage automatique.
        /// </summary>
        internal static string EnableAutoBootMode {
            get {
                return ResourceManager.GetString("EnableAutoBootMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activer l&apos;empilement de Mod.
        /// </summary>
        internal static string EnableModStacking {
            get {
                return ResourceManager.GetString("EnableModStacking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOTE : Pour les versions de A.I.R.
        /// </summary>
        internal static string EnableModStacking_Note1 {
            get {
                return ResourceManager.GetString("EnableModStacking_Note1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v19.09.19.0 et plus récent.
        /// </summary>
        internal static string EnableModStacking_Note2 {
            get {
                return ResourceManager.GetString("EnableModStacking_Note2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrer l&apos;URL du Mod ....
        /// </summary>
        internal static string EnterModURL {
            get {
                return ResourceManager.GetString("EnterModURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur de chargement.
        /// </summary>
        internal static string ErrorWithLoading {
            get {
                return ResourceManager.GetString("ErrorWithLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eukaryot3K @ Twitter.
        /// </summary>
        internal static string Eukaryot3KTwitter {
            get {
                return ResourceManager.GetString("Eukaryot3KTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fichier executable.
        /// </summary>
        internal static string EXEFileDialogFilter {
            get {
                return ResourceManager.GetString("EXEFileDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélectionner le fichier EXE (de Lancement) de Sonic 3 A.I.R....
        /// </summary>
        internal static string EXEFileDialogTitle {
            get {
                return ResourceManager.GetString("EXEFileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quitter.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporter....
        /// </summary>
        internal static string ExportExpanable {
            get {
                return ResourceManager.GetString("ExportExpanable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode sans échec.
        /// </summary>
        internal static string FailSafeMode {
            get {
                return ResourceManager.GetString("FailSafeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correction des problèmes.
        /// </summary>
        internal static string FixGlitches {
            get {
                return ResourceManager.GetString("FixGlitches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Démarrage forcé.
        /// </summary>
        internal static string ForceStart {
            get {
                return ResourceManager.GetString("ForceStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les options de Gamebanana URL Handler....
        /// </summary>
        internal static string GameBannaURLHandler {
            get {
                return ResourceManager.GetString("GameBannaURLHandler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le jeu a été installé dans.
        /// </summary>
        internal static string GameInstalledAt {
            get {
                return ResourceManager.GetString("GameInstalledAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Général.
        /// </summary>
        internal static string GeneralTab {
            get {
                return ResourceManager.GetString("GeneralTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guides/Raccourcis.
        /// </summary>
        internal static string GuidesTab {
            get {
                return ResourceManager.GetString("GuidesTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID:.
        /// </summary>
        internal static string IDLabel {
            get {
                return ResourceManager.GetString("IDLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importer....
        /// </summary>
        internal static string ImportExpandable {
            get {
                return ResourceManager.GetString("ImportExpandable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Augmenter la priorité du Mod sélectionné....
        /// </summary>
        internal static string IncreaseModPriority {
            get {
                return ResourceManager.GetString("IncreaseModPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Augmenter la priorité du mod sélectionné sur Max....
        /// </summary>
        internal static string IncreaseModPriorityToMax {
            get {
                return ResourceManager.GetString("IncreaseModPriorityToMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [INPUT].
        /// </summary>
        internal static string Input_INPUT {
            get {
                return ResourceManager.GetString("Input_INPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [MULTI].
        /// </summary>
        internal static string Input_MULTI {
            get {
                return ResourceManager.GetString("Input_MULTI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AUCUN].
        /// </summary>
        internal static string Input_NONE {
            get {
                return ResourceManager.GetString("Input_NONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [NULL].
        /// </summary>
        internal static string Input_NULL {
            get {
                return ResourceManager.GetString("Input_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [NON-SUPPORTÉ].
        /// </summary>
        internal static string Input_UNSUPPORTED {
            get {
                return ResourceManager.GetString("Input_UNSUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur lors du chargement du fichier de configuration des inputs !
        ///Assurez-vous que votre jeu est à jour et que le chemin du jeu A.I.R est défini dans Options..
        /// </summary>
        internal static string InputMappingError1 {
            get {
                return ResourceManager.GetString("InputMappingError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une erreur s&apos;est produite lors de la lecture du fichier de configuration dans le dossier de cette version !
        ///Assurez-vous que le fichier de configuration n&apos;est pas endommagé ou effectuez une réinstallation  de cette version de A.I.R.
        /// </summary>
        internal static string InputMappingError2 {
            get {
                return ResourceManager.GetString("InputMappingError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le fichier de configuration n&apos;existe pas dans le dossier A.I.R du fichier EXE.
        ///  Assurez-vous que le fichier existe ou réinstaller cette version de A.I.R.
        /// </summary>
        internal static string InputMappingError3 {
            get {
                return ResourceManager.GetString("InputMappingError3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        internal static string InputTab {
            get {
                return ResourceManager.GetString("InputTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versions installées.
        /// </summary>
        internal static string InstalledVersions {
            get {
                return ResourceManager.GetString("InstalledVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL incorrect.
        /// </summary>
        internal static string InvalidURL {
            get {
                return ResourceManager.GetString("InvalidURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélectionner la manette....
        /// </summary>
        internal static string JoystickInputSelectorFormTitle {
            get {
                return ResourceManager.GetString("JoystickInputSelectorFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Probablement une erreur du JSON; Assurez-vous que le fichier mod.json est correctement formaté !).
        /// </summary>
        internal static string JSONErrorPossible {
            get {
                return ResourceManager.GetString("JSONErrorPossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Existant).
        /// </summary>
        internal static string KeybindingsExistingNote {
            get {
                return ResourceManager.GetString("KeybindingsExistingNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raccourcis clavier :.
        /// </summary>
        internal static string KeybindingsLabel {
            get {
                return ResourceManager.GetString("KeybindingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clavier.
        /// </summary>
        internal static string KeyboardRadioButton {
            get {
                return ResourceManager.GetString("KeyboardRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touche :.
        /// </summary>
        internal static string KeyLabel {
            get {
                return ResourceManager.GetString("KeyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La langue :.
        /// </summary>
        internal static string LanguageLabel {
            get {
                return ResourceManager.GetString("LanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fichier journal non trouvé.
        /// </summary>
        internal static string LogFileNotFound {
            get {
                return ResourceManager.GetString("LogFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;emplacement du fichier de Sonic 3 A.I.R n&apos;est pas défini, souhaitez-vous le configurer maintenant ?.
        /// </summary>
        internal static string MissingAIRSetNowAlert {
            get {
                return ResourceManager.GetString("MissingAIRSetNowAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod de Sonic 3 AIR.
        /// </summary>
        internal static string ModFileDialogFilter {
            get {
                return ResourceManager.GetString("ModFileDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélectionner le fichier compressé....
        /// </summary>
        internal static string ModFileDialogTitle {
            get {
                return ResourceManager.GetString("ModFileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options du Mod Manager.
        /// </summary>
        internal static string ModManagerOptions {
            get {
                return ResourceManager.GetString("ModManagerOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version du Mod Manager.
        /// </summary>
        internal static string ModManagerVersion {
            get {
                return ResourceManager.GetString("ModManagerVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mods.
        /// </summary>
        internal static string ModsTab {
            get {
                return ResourceManager.GetString("ModsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Propriétés du Mod .
        /// </summary>
        internal static string ModsTab_ModProperties {
            get {
                return ResourceManager.GetString("ModsTab_ModProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plus....
        /// </summary>
        internal static string MoreExpandable {
            get {
                return ResourceManager.GetString("MoreExpandable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non.
        /// </summary>
        internal static string No_Button {
            get {
                return ResourceManager.GetString("No_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucune manette de jeu n&apos;a été détectée !.
        /// </summary>
        internal static string NoControllerFound {
            get {
                return ResourceManager.GetString("NoControllerFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucune version installée.
        /// </summary>
        internal static string NoInstalledVersions {
            get {
                return ResourceManager.GetString("NoInstalledVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucune description fournie..
        /// </summary>
        internal static string NoModDescript {
            get {
                return ResourceManager.GetString("NoModDescript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;OK.
        /// </summary>
        internal static string Ok_Button {
            get {
                return ResourceManager.GetString("Ok_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ouvrir.
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ouvrir le dossier AppData.
        /// </summary>
        internal static string OpenAppDataFolder {
            get {
                return ResourceManager.GetString("OpenAppDataFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ouvrir le fichier de configuration.
        /// </summary>
        internal static string OpenConfigFile {
            get {
                return ResourceManager.GetString("OpenConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ouvrir le dossier de téléchargement.
        /// </summary>
        internal static string OpenDownloadsFolder {
            get {
                return ResourceManager.GetString("OpenDownloadsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ouvrir le dossier du fichier EXE.
        /// </summary>
        internal static string OpenEXEFolder {
            get {
                return ResourceManager.GetString("OpenEXEFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ouvrir l&apos;emplacement du fichier....
        /// </summary>
        internal static string OpenLocationExpandable {
            get {
                return ResourceManager.GetString("OpenLocationExpandable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ouvrir le dossier du Mod.
        /// </summary>
        internal static string OpenModFolder {
            get {
                return ResourceManager.GetString("OpenModFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les instructions de Modding sur Sonic 3 A.I.R.
        /// </summary>
        internal static string OpenModInstructions {
            get {
                return ResourceManager.GetString("OpenModInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ouvrir le dossier des Mods.
        /// </summary>
        internal static string OpenModsFolder {
            get {
                return ResourceManager.GetString("OpenModsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ouvrir le dossier du modèle de modding.
        /// </summary>
        internal static string OpenModTemplatesFolder {
            get {
                return ResourceManager.GetString("OpenModTemplatesFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ouvrir l&apos;URL du Mod.
        /// </summary>
        internal static string OpenModURL {
            get {
                return ResourceManager.GetString("OpenModURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ouvrir l&apos;exemple du dossier Mods.
        /// </summary>
        internal static string OpenSampleModsFolder {
            get {
                return ResourceManager.GetString("OpenSampleModsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ouvrir le fichier de configuration.
        /// </summary>
        internal static string OpenSettingsFile {
            get {
                return ResourceManager.GetString("OpenSettingsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ouvrir les paramètres système....
        /// </summary>
        internal static string OpenSystemSettingsExpandable {
            get {
                return ResourceManager.GetString("OpenSystemSettingsExpandable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le manuel d&apos;utilisation de Sonic 3 A.I.R.
        /// </summary>
        internal static string OpenUserManual {
            get {
                return ResourceManager.GetString("OpenUserManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ouvrir le dossier des versions.
        /// </summary>
        internal static string OpenVersionsFolder {
            get {
                return ResourceManager.GetString("OpenVersionsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emplacement.
        /// </summary>
        internal static string PathColumnHeader {
            get {
                return ResourceManager.GetString("PathColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez actualiser la liste de Mod !.
        /// </summary>
        internal static string PleaseRefreshTheModList {
            get {
                return ResourceManager.GetString("PleaseRefreshTheModList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POV.
        /// </summary>
        internal static string POVRadioButton {
            get {
                return ResourceManager.GetString("POVRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raison.
        /// </summary>
        internal static string Reason {
            get {
                return ResourceManager.GetString("Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chemin du fichier d’enregistrement copié dans le Presse-papiers !.
        /// </summary>
        internal static string RecordingPathCopiedToClipboard {
            get {
                return ResourceManager.GetString("RecordingPathCopiedToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enregistrements(captures) du jeu.
        /// </summary>
        internal static string RecordingsTab {
            get {
                return ResourceManager.GetString("RecordingsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le fichier téléchargé sur File.io expirera dans 1 semaine, il sera utilisé qu&apos;une seule fois :.
        /// </summary>
        internal static string RecordingUploaded1 {
            get {
                return ResourceManager.GetString("RecordingUploaded1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (L&apos;URL a été copiée dans le presse-papiers) :.
        /// </summary>
        internal static string RecordingUploaded2 {
            get {
                return ResourceManager.GetString("RecordingUploaded2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rafraîchir.
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relancer.
        /// </summary>
        internal static string Reload {
            get {
                return ResourceManager.GetString("Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retirer.
        /// </summary>
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vérification: voulez-vous retirer.
        /// </summary>
        internal static string RemoveInputDeviceConfirmation1 {
            get {
                return ResourceManager.GetString("RemoveInputDeviceConfirmation1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de la liste des périphériques acceptables pour cet Input ?.
        /// </summary>
        internal static string RemoveInputDeviceConfirmation2 {
            get {
                return ResourceManager.GetString("RemoveInputDeviceConfirmation2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retirer le Mod.
        /// </summary>
        internal static string RemoveMod {
            get {
                return ResourceManager.GetString("RemoveMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retirer le Mod sélectionné....
        /// </summary>
        internal static string RemoveSelectedMod {
            get {
                return ResourceManager.GetString("RemoveSelectedMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Êtes-vous sûr de vouloir retirer cette version.
        /// </summary>
        internal static string RemoveVersionConfirmation {
            get {
                return ResourceManager.GetString("RemoveVersionConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resélectionner l&apos;input.
        /// </summary>
        internal static string Reselect_Input_Button {
            get {
                return ResourceManager.GetString("Reselect_Input_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Êtes-vous sûr d&apos;aller plus loin ? Vos modifications actuelles seront perdues!.
        /// </summary>
        internal static string ResetInputMappingsDefaultFormMessage {
            get {
                return ResourceManager.GetString("ResetInputMappingsDefaultFormMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réinitialiser le réglage des boutons.
        /// </summary>
        internal static string ResetInputMappingsDefaultFormTitle {
            get {
                return ResourceManager.GetString("ResetInputMappingsDefaultFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réinitialiser par défaut.
        /// </summary>
        internal static string ResetMappingsToDefaultButton {
            get {
                return ResourceManager.GetString("ResetMappingsToDefaultButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Résultat :.
        /// </summary>
        internal static string ResultLabel {
            get {
                return ResourceManager.GetString("ResultLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3AIR @ Gamebanana.
        /// </summary>
        internal static string S3AIRGB {
            get {
                return ResourceManager.GetString("S3AIRGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page d&apos;accueil de Sonic 3 A.I.R.
        /// </summary>
        internal static string S3AIRHomepage {
            get {
                return ResourceManager.GetString("S3AIRHomepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;emplacement de Sonic 3 A.I.R. n&apos;est pas défini !.
        /// </summary>
        internal static string S3AIRPathNotSet {
            get {
                return ResourceManager.GetString("S3AIRPathNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emplacement de la ROM Sonic 3K :.
        /// </summary>
        internal static string S3KROMPathLabel {
            get {
                return ResourceManager.GetString("S3KROMPathLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sauvegarder.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sauvegarder et Charger.
        /// </summary>
        internal static string Save_Load {
            get {
                return ResourceManager.GetString("Save&Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enregistrer le réglage des boutons.
        /// </summary>
        internal static string SaveInputMappingsButton {
            get {
                return ResourceManager.GetString("SaveInputMappingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selectionner.
        /// </summary>
        internal static string Select_Button {
            get {
                return ResourceManager.GetString("Select_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélectionnez dans &quot;Installer&quot; la version de A.I.R....
        /// </summary>
        internal static string SelectFromInstalledVersions {
            get {
                return ResourceManager.GetString("SelectFromInstalledVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selectionner l&apos;Input.
        /// </summary>
        internal static string SelectInputTitleExpandable {
            get {
                return ResourceManager.GetString("SelectInputTitleExpandable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélectionnez/Installez à partir d&apos;une version archivée(ZIP) de A.I.R....
        /// </summary>
        internal static string SelectInstallFromAIRZIP {
            get {
                return ResourceManager.GetString("SelectInstallFromAIRZIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choisir le dossier de la ROM Sonic 3K....
        /// </summary>
        internal static string SelectSonic3KRomFile {
            get {
                return ResourceManager.GetString("SelectSonic3KRomFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choisir l&apos;archive(Zip) de Sonic 3 A.I.R....
        /// </summary>
        internal static string SelectSonicAIRVersionZIP {
            get {
                return ResourceManager.GetString("SelectSonicAIRVersionZIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Régler l&apos;emplacement du fichier de paramètre de A.I.R....
        /// </summary>
        internal static string SetAIRPathFromSettings {
            get {
                return ResourceManager.GetString("SetAIRPathFromSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Régler manuellement (Classique) l&apos;emplacement du fichier de paramètre de A.I.R....
        /// </summary>
        internal static string SetAIRPathManuallyClassic {
            get {
                return ResourceManager.GetString("SetAIRPathManuallyClassic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtenir/Définir à partir de versions installées :.
        /// </summary>
        internal static string SetFromInstalledHeader {
            get {
                return ResourceManager.GetString("SetFromInstalledHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Régler Manuellement :.
        /// </summary>
        internal static string SetManuallyHeader {
            get {
                return ResourceManager.GetString("SetManuallyHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paramètres.
        /// </summary>
        internal static string SettingsTab {
            get {
                return ResourceManager.GetString("SettingsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version des paramètres de A.I.R..
        /// </summary>
        internal static string SettingsVersionLabel {
            get {
                return ResourceManager.GetString("SettingsVersionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher le fichier journal.
        /// </summary>
        internal static string ShowLogFileButton {
            get {
                return ResourceManager.GetString("ShowLogFileButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emplacement de Sonic 3 A.I.R :.
        /// </summary>
        internal static string Sonic3AIRPathLabel {
            get {
                return ResourceManager.GetString("Sonic3AIRPathLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dossier de la ROM Sonic 3K.
        /// </summary>
        internal static string Sonic3KRomFile {
            get {
                return ResourceManager.GetString("Sonic3KRomFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive(Zip) de Sonic 3 A.I.R.
        /// </summary>
        internal static string SonicAIRVersionZIP {
            get {
                return ResourceManager.GetString("SonicAIRVersionZIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le fichier ou le répertoire spécifié n&apos;existe pas !.
        /// </summary>
        internal static string SpecifiedFileDirNotExist {
            get {
                return ResourceManager.GetString("SpecifiedFileDirNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La version de Sonic 3 A.I.R est obsolète, veuillez utiliser la version 19.08.17.0 ou une version ultérieure ! (Sans oublier de le démarrer au moins une fois !).
        /// </summary>
        internal static string StartupFailureError {
            get {
                return ResourceManager.GetString("StartupFailureError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laisser ouvert quand je quitte le jeu.
        /// </summary>
        internal static string StayOpenOnExit {
            get {
                return ResourceManager.GetString("StayOpenOnExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laisser ouvert quand je lance le jeu.
        /// </summary>
        internal static string StayOpenOnLoad {
            get {
                return ResourceManager.GetString("StayOpenOnLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pouce.
        /// </summary>
        internal static string ThumbstickRadioButton {
            get {
                return ResourceManager.GetString("ThumbstickRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objet.
        /// </summary>
        internal static string TimestampColumnHeader {
            get {
                return ResourceManager.GetString("TimestampColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outils.
        /// </summary>
        internal static string ToolsTab {
            get {
                return ResourceManager.GetString("ToolsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string TypeGB {
            get {
                return ResourceManager.GetString("TypeGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de supprimer le fichier !.
        /// </summary>
        internal static string UnableToDeleteFile {
            get {
                return ResourceManager.GetString("UnableToDeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de supprimer cette version !.
        /// </summary>
        internal static string UnableToRemoveVersion {
            get {
                return ResourceManager.GetString("UnableToRemoveVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de valider l&apos;emplacement.
        /// </summary>
        internal static string UnableToValididatePath {
            get {
                return ResourceManager.GetString("UnableToValididatePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une mise à jour est disponible! Souhaitez-vous mettre à jour maintenant ?.
        /// </summary>
        internal static string UpdateAvaliable {
            get {
                return ResourceManager.GetString("UpdateAvaliable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une mise à jour est disponible ! Souhaitez-vous mettre à jour maintenant ?.
        /// </summary>
        internal static string Updater_Avaliable {
            get {
                return ResourceManager.GetString("Updater_Avaliable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous avez la dernière version. Voulez-vous la retélécharger ?.
        /// </summary>
        internal static string Updater_UpToDate {
            get {
                return ResourceManager.GetString("Updater_UpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mise à jour.
        /// </summary>
        internal static string UpdaterTitle {
            get {
                return ResourceManager.GetString("UpdaterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importer.
        /// </summary>
        internal static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raccourcis/Touches utiles dans le jeu :
        ///
        ///Alt + Entrée - Basculer en plein écran
        ///F2 - Faire une capture(enregistrement) du jeu
        ///Clic droit - Ouvrir le menu contextuel de A.I.R
        ///F3 - Rescanner pour les manettes de jeu
        ///F4 - Échanger les contrôles des manettes J1 et J2
        ///Pavé numérique Plus/Moins - Ajuster le volume audio global
        ///Alt + B - Changer le flou d&apos;arrière-plan
        ///Alt + F - Changer le filtre
        ///Alt + P - Afficher les performances.
        /// </summary>
        internal static string UsefulShortKeys {
            get {
                return ResourceManager.GetString("UsefulShortKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string VersionColumnHeader {
            get {
                return ResourceManager.GetString("VersionColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versions.
        /// </summary>
        internal static string VersionsTab {
            get {
                return ResourceManager.GetString("VersionsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En attente de l&apos;input....
        /// </summary>
        internal static string WaitingForInputDialogLabel {
            get {
                return ResourceManager.GetString("WaitingForInputDialogLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input sélectionnée :.
        /// </summary>
        internal static string WaitingForInputDialogLabelTag {
            get {
                return ResourceManager.GetString("WaitingForInputDialogLabelTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oui.
        /// </summary>
        internal static string Yes_Button {
            get {
                return ResourceManager.GetString("Yes_Button", resourceCulture);
            }
        }
    }
}
