//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sonic3AIR_ModManager.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class lang_null {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang_null() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sonic3AIR_ModManager.Languages.lang.null", typeof(lang_null).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string AboutString {
            get {
                return ResourceManager.GetString("AboutString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string AboutTab {
            get {
                return ResourceManager.GetString("AboutTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string AddAMod {
            get {
                return ResourceManager.GetString("AddAMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string AddInputDeviceDialogCaption {
            get {
                return ResourceManager.GetString("AddInputDeviceDialogCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string AddInputDeviceDialogTitle {
            get {
                return ResourceManager.GetString("AddInputDeviceDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string AddInputDeviceError1 {
            get {
                return ResourceManager.GetString("AddInputDeviceError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string AddInputDeviceError2 {
            get {
                return ResourceManager.GetString("AddInputDeviceError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string AddNewDeviceDescription {
            get {
                return ResourceManager.GetString("AddNewDeviceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string AddNewDeviceTitle {
            get {
                return ResourceManager.GetString("AddNewDeviceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string AddNewSubFolderButton {
            get {
                return ResourceManager.GetString("AddNewSubFolderButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string AIRCanNotStartNoPath {
            get {
                return ResourceManager.GetString("AIRCanNotStartNoPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string AIRChangePathNoLongerExists {
            get {
                return ResourceManager.GetString("AIRChangePathNoLongerExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string AIRDevMode {
            get {
                return ResourceManager.GetString("AIRDevMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string AIRGuides {
            get {
                return ResourceManager.GetString("AIRGuides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string AIRInternalSettings {
            get {
                return ResourceManager.GetString("AIRInternalSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string AIRLaunchOptionsGroupHeader {
            get {
                return ResourceManager.GetString("AIRLaunchOptionsGroupHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string AIRMedia {
            get {
                return ResourceManager.GetString("AIRMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string AIRMMPlaces {
            get {
                return ResourceManager.GetString("AIRMMPlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string AIROptionsTab {
            get {
                return ResourceManager.GetString("AIROptionsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string AIRPlaces {
            get {
                return ResourceManager.GetString("AIRPlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string AIRTips {
            get {
                return ResourceManager.GetString("AIRTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string AIRVersion {
            get {
                return ResourceManager.GetString("AIRVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string AIRVersionColumnHeader {
            get {
                return ResourceManager.GetString("AIRVersionColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string ArchitectureString {
            get {
                return ResourceManager.GetString("ArchitectureString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string AuthorSection {
            get {
                return ResourceManager.GetString("AuthorSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string AutoBoot_CheckingForUpdates {
            get {
                return ResourceManager.GetString("AutoBoot_CheckingForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string AutoBoot_Initalizing {
            get {
                return ResourceManager.GetString("AutoBoot_Initalizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string AutoBoot_LaunchingIn {
            get {
                return ResourceManager.GetString("AutoBoot_LaunchingIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string AutoBootDelay {
            get {
                return ResourceManager.GetString("AutoBootDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string AxisPOVLabel {
            get {
                return ResourceManager.GetString("AxisPOVLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string AxisRadioButton {
            get {
                return ResourceManager.GetString("AxisRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string BackupFailed {
            get {
                return ResourceManager.GetString("BackupFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string BuildDateString {
            get {
                return ResourceManager.GetString("BuildDateString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string ButtonLabel {
            get {
                return ResourceManager.GetString("ButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string ButtonMappings {
            get {
                return ResourceManager.GetString("ButtonMappings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string Buttons_A {
            get {
                return ResourceManager.GetString("Buttons_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string Buttons_B {
            get {
                return ResourceManager.GetString("Buttons_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string Buttons_Back {
            get {
                return ResourceManager.GetString("Buttons_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string Buttons_Down {
            get {
                return ResourceManager.GetString("Buttons_Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string Buttons_Left {
            get {
                return ResourceManager.GetString("Buttons_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string Buttons_Right {
            get {
                return ResourceManager.GetString("Buttons_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string Buttons_Start {
            get {
                return ResourceManager.GetString("Buttons_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string Buttons_Up {
            get {
                return ResourceManager.GetString("Buttons_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string Buttons_X {
            get {
                return ResourceManager.GetString("Buttons_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string Buttons_Y {
            get {
                return ResourceManager.GetString("Buttons_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string By {
            get {
                return ResourceManager.GetString("By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string Cancel_Button {
            get {
                return ResourceManager.GetString("Cancel_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string CarJemTwitter {
            get {
                return ResourceManager.GetString("CarJemTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string CheckforAIRUpdatesOnStart {
            get {
                return ResourceManager.GetString("CheckforAIRUpdatesOnStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string CheckForGameUpdatesExpandable {
            get {
                return ResourceManager.GetString("CheckForGameUpdatesExpandable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string CheckForModManagerUpdatesButton {
            get {
                return ResourceManager.GetString("CheckForModManagerUpdatesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string CollectionFilesCouldNotBeFound1 {
            get {
                return ResourceManager.GetString("CollectionFilesCouldNotBeFound1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string CollectionFilesCouldNotBeFound2 {
            get {
                return ResourceManager.GetString("CollectionFilesCouldNotBeFound2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string CollectionFilesCouldNotBeFound3 {
            get {
                return ResourceManager.GetString("CollectionFilesCouldNotBeFound3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string ConflictDialogCaption {
            get {
                return ResourceManager.GetString("ConflictDialogCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string ConflictingModSection {
            get {
                return ResourceManager.GetString("ConflictingModSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string ControllerRadioButton {
            get {
                return ResourceManager.GetString("ControllerRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string CopyFilePath {
            get {
                return ResourceManager.GetString("CopyFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string CreateSubFolderDialogCaption1 {
            get {
                return ResourceManager.GetString("CreateSubFolderDialogCaption1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string CreateSubFolderDialogCaption2 {
            get {
                return ResourceManager.GetString("CreateSubFolderDialogCaption2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string CreateSubFolderDialogTitle {
            get {
                return ResourceManager.GetString("CreateSubFolderDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string CurrentFolderLabel {
            get {
                return ResourceManager.GetString("CurrentFolderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string CustomAdvancedLabel {
            get {
                return ResourceManager.GetString("CustomAdvancedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string CustomStringLabel {
            get {
                return ResourceManager.GetString("CustomStringLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string CustomWordString {
            get {
                return ResourceManager.GetString("CustomWordString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string DecreaseModPriority {
            get {
                return ResourceManager.GetString("DecreaseModPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string DecreaseModPriorityToMin {
            get {
                return ResourceManager.GetString("DecreaseModPriorityToMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string DefaultLaunchOptionItemText {
            get {
                return ResourceManager.GetString("DefaultLaunchOptionItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string DeleteDeviceTitle {
            get {
                return ResourceManager.GetString("DeleteDeviceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string DeleteItemConfirmation {
            get {
                return ResourceManager.GetString("DeleteItemConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string DeleteKeybindTitle {
            get {
                return ResourceManager.GetString("DeleteKeybindTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string DeleteKeybindVerification1 {
            get {
                return ResourceManager.GetString("DeleteKeybindVerification1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string DeleteKeybindVerification2 {
            get {
                return ResourceManager.GetString("DeleteKeybindVerification2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string DetectControllerExpandable {
            get {
                return ResourceManager.GetString("DetectControllerExpandable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string DetectGamepadInputExpandable {
            get {
                return ResourceManager.GetString("DetectGamepadInputExpandable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string DeviceIdentifierNames {
            get {
                return ResourceManager.GetString("DeviceIdentifierNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string DirectionGB {
            get {
                return ResourceManager.GetString("DirectionGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string DoesNotExist {
            get {
                return ResourceManager.GetString("DoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string Downloading {
            get {
                return ResourceManager.GetString("Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string EditExpandable {
            get {
                return ResourceManager.GetString("EditExpandable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string EditKeybindingsTitleExpandable {
            get {
                return ResourceManager.GetString("EditKeybindingsTitleExpandable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string EnableAutoBootMode {
            get {
                return ResourceManager.GetString("EnableAutoBootMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string EnableModStacking {
            get {
                return ResourceManager.GetString("EnableModStacking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string EnableModStacking_Note1 {
            get {
                return ResourceManager.GetString("EnableModStacking_Note1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string EnableModStacking_Note2 {
            get {
                return ResourceManager.GetString("EnableModStacking_Note2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string EnterModURL {
            get {
                return ResourceManager.GetString("EnterModURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string ErrorHyperlinkClickMessage {
            get {
                return ResourceManager.GetString("ErrorHyperlinkClickMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string ErrorWithLoading {
            get {
                return ResourceManager.GetString("ErrorWithLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string Eukaryot3KTwitter {
            get {
                return ResourceManager.GetString("Eukaryot3KTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string EXEFileDialogFilter {
            get {
                return ResourceManager.GetString("EXEFileDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string EXEFileDialogTitle {
            get {
                return ResourceManager.GetString("EXEFileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string ExistingModSection {
            get {
                return ResourceManager.GetString("ExistingModSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string ExportExpanable {
            get {
                return ResourceManager.GetString("ExportExpanable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string FailSafeMode {
            get {
                return ResourceManager.GetString("FailSafeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string FileIsBusyCaption {
            get {
                return ResourceManager.GetString("FileIsBusyCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string FileIsBusyTitle {
            get {
                return ResourceManager.GetString("FileIsBusyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string FileString {
            get {
                return ResourceManager.GetString("FileString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string FixGlitches {
            get {
                return ResourceManager.GetString("FixGlitches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string FolderString {
            get {
                return ResourceManager.GetString("FolderString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string ForceStart {
            get {
                return ResourceManager.GetString("ForceStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string FullscreenOption1 {
            get {
                return ResourceManager.GetString("FullscreenOption1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string FullscreenOption2 {
            get {
                return ResourceManager.GetString("FullscreenOption2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string FullscreenOption3 {
            get {
                return ResourceManager.GetString("FullscreenOption3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string GameBannaURLHandler {
            get {
                return ResourceManager.GetString("GameBannaURLHandler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string GameInstalledAt {
            get {
                return ResourceManager.GetString("GameInstalledAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string GameVersionSection {
            get {
                return ResourceManager.GetString("GameVersionSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string GeneralTab {
            get {
                return ResourceManager.GetString("GeneralTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string GuidesTab {
            get {
                return ResourceManager.GetString("GuidesTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string IDLabel {
            get {
                return ResourceManager.GetString("IDLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string ImportExpandable {
            get {
                return ResourceManager.GetString("ImportExpandable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string IncreaseModPriority {
            get {
                return ResourceManager.GetString("IncreaseModPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string IncreaseModPriorityToMax {
            get {
                return ResourceManager.GetString("IncreaseModPriorityToMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string Input_INPUT {
            get {
                return ResourceManager.GetString("Input_INPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string Input_MULTI {
            get {
                return ResourceManager.GetString("Input_MULTI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string Input_NONE {
            get {
                return ResourceManager.GetString("Input_NONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string Input_NULL {
            get {
                return ResourceManager.GetString("Input_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string Input_UNSUPPORTED {
            get {
                return ResourceManager.GetString("Input_UNSUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string InputMappingError1 {
            get {
                return ResourceManager.GetString("InputMappingError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string InputMappingError2 {
            get {
                return ResourceManager.GetString("InputMappingError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string InputMappingError3 {
            get {
                return ResourceManager.GetString("InputMappingError3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string InputTab {
            get {
                return ResourceManager.GetString("InputTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string InstalledVersions {
            get {
                return ResourceManager.GetString("InstalledVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string InvalidURL {
            get {
                return ResourceManager.GetString("InvalidURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string JoystickInputSelectorFormTitle {
            get {
                return ResourceManager.GetString("JoystickInputSelectorFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string JSONErrorPossible {
            get {
                return ResourceManager.GetString("JSONErrorPossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string KeybindingsExistingNote {
            get {
                return ResourceManager.GetString("KeybindingsExistingNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string KeybindingsLabel {
            get {
                return ResourceManager.GetString("KeybindingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string KeyboardRadioButton {
            get {
                return ResourceManager.GetString("KeyboardRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string KeyLabel {
            get {
                return ResourceManager.GetString("KeyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string LanguageLabel {
            get {
                return ResourceManager.GetString("LanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string LaunchOptionsForewarning {
            get {
                return ResourceManager.GetString("LaunchOptionsForewarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string LaunchOptionsPlayerK {
            get {
                return ResourceManager.GetString("LaunchOptionsPlayerK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string LaunchOptionsPlayerKT {
            get {
                return ResourceManager.GetString("LaunchOptionsPlayerKT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string LaunchOptionsPlayerS {
            get {
                return ResourceManager.GetString("LaunchOptionsPlayerS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string LaunchOptionsPlayerST {
            get {
                return ResourceManager.GetString("LaunchOptionsPlayerST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string LaunchOptionsPlayerT {
            get {
                return ResourceManager.GetString("LaunchOptionsPlayerT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string LaunchOptionsStartingPhaseLabel {
            get {
                return ResourceManager.GetString("LaunchOptionsStartingPhaseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string LaunchOptionsStartingPlayerLabel {
            get {
                return ResourceManager.GetString("LaunchOptionsStartingPlayerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string LaunchOptionsStartingSceneLabel {
            get {
                return ResourceManager.GetString("LaunchOptionsStartingSceneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string LaunchOptionsWarning1 {
            get {
                return ResourceManager.GetString("LaunchOptionsWarning1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string LaunchOptionsWarning2 {
            get {
                return ResourceManager.GetString("LaunchOptionsWarning2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string LogFileNotFound {
            get {
                return ResourceManager.GetString("LogFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string MakeCopyButton {
            get {
                return ResourceManager.GetString("MakeCopyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string MissingAIRSetNowAlert {
            get {
                return ResourceManager.GetString("MissingAIRSetNowAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string ModFileDialogFilter {
            get {
                return ResourceManager.GetString("ModFileDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string ModFileDialogTitle {
            get {
                return ResourceManager.GetString("ModFileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string ModManagerOptions {
            get {
                return ResourceManager.GetString("ModManagerOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string ModManagerVersion {
            get {
                return ResourceManager.GetString("ModManagerVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string ModsLoadingError {
            get {
                return ResourceManager.GetString("ModsLoadingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string ModsTab {
            get {
                return ResourceManager.GetString("ModsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string ModsTab_ModProperties {
            get {
                return ResourceManager.GetString("ModsTab_ModProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string ModVersionSection {
            get {
                return ResourceManager.GetString("ModVersionSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string MoreExpandable {
            get {
                return ResourceManager.GetString("MoreExpandable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string NameSection {
            get {
                return ResourceManager.GetString("NameSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string NewControllerEntryName {
            get {
                return ResourceManager.GetString("NewControllerEntryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string NewDeviceEntryName {
            get {
                return ResourceManager.GetString("NewDeviceEntryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string NewStrings {
            get {
                return ResourceManager.GetString("NewStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string NewSubFolderEntryName {
            get {
                return ResourceManager.GetString("NewSubFolderEntryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string No_Button {
            get {
                return ResourceManager.GetString("No_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string NoControllerFound {
            get {
                return ResourceManager.GetString("NoControllerFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string NoInstalledVersions {
            get {
                return ResourceManager.GetString("NoInstalledVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string NoModDescript {
            get {
                return ResourceManager.GetString("NoModDescript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string Ok_Button {
            get {
                return ResourceManager.GetString("Ok_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string OpenAppDataFolder {
            get {
                return ResourceManager.GetString("OpenAppDataFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string OpenConfigFile {
            get {
                return ResourceManager.GetString("OpenConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string OpenDownloadsFolder {
            get {
                return ResourceManager.GetString("OpenDownloadsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string OpenEXEFolder {
            get {
                return ResourceManager.GetString("OpenEXEFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string OpenExternally {
            get {
                return ResourceManager.GetString("OpenExternally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string OpenLocationExpandable {
            get {
                return ResourceManager.GetString("OpenLocationExpandable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string OpenModFolder {
            get {
                return ResourceManager.GetString("OpenModFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string OpenModInstructions {
            get {
                return ResourceManager.GetString("OpenModInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string OpenModsFolder {
            get {
                return ResourceManager.GetString("OpenModsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string OpenModTemplatesFolder {
            get {
                return ResourceManager.GetString("OpenModTemplatesFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string OpenModURL {
            get {
                return ResourceManager.GetString("OpenModURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string OpenSampleModsFolder {
            get {
                return ResourceManager.GetString("OpenSampleModsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string OpenSettingsFile {
            get {
                return ResourceManager.GetString("OpenSettingsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string OpenSystemSettingsExpandable {
            get {
                return ResourceManager.GetString("OpenSystemSettingsExpandable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string OpenUserManual {
            get {
                return ResourceManager.GetString("OpenUserManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string OpenVersionsFolder {
            get {
                return ResourceManager.GetString("OpenVersionsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string OverwriteButton {
            get {
                return ResourceManager.GetString("OverwriteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string PathColumnHeader {
            get {
                return ResourceManager.GetString("PathColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string PleaseRefreshTheModList {
            get {
                return ResourceManager.GetString("PleaseRefreshTheModList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string POVRadioButton {
            get {
                return ResourceManager.GetString("POVRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string Reason {
            get {
                return ResourceManager.GetString("Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string RecordingPathCopiedToClipboard {
            get {
                return ResourceManager.GetString("RecordingPathCopiedToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string RecordingsLoadingError {
            get {
                return ResourceManager.GetString("RecordingsLoadingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string RecordingsLocationAppData {
            get {
                return ResourceManager.GetString("RecordingsLocationAppData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string RecordingsLocationBrowse {
            get {
                return ResourceManager.GetString("RecordingsLocationBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string RecordingsLocationDefault {
            get {
                return ResourceManager.GetString("RecordingsLocationDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string RecordingsLocationEXEFolder {
            get {
                return ResourceManager.GetString("RecordingsLocationEXEFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string RecordingsLocationLabel {
            get {
                return ResourceManager.GetString("RecordingsLocationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string RecordingsLocationRecordingsFolder {
            get {
                return ResourceManager.GetString("RecordingsLocationRecordingsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string RecordingsTab {
            get {
                return ResourceManager.GetString("RecordingsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string RecordingUploaded1 {
            get {
                return ResourceManager.GetString("RecordingUploaded1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string RecordingUploaded2 {
            get {
                return ResourceManager.GetString("RecordingUploaded2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string Reload {
            get {
                return ResourceManager.GetString("Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string RemoveCurrentFolderButton {
            get {
                return ResourceManager.GetString("RemoveCurrentFolderButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string RemoveInputDeviceConfirmation1 {
            get {
                return ResourceManager.GetString("RemoveInputDeviceConfirmation1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string RemoveInputDeviceConfirmation2 {
            get {
                return ResourceManager.GetString("RemoveInputDeviceConfirmation2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string RemoveMod {
            get {
                return ResourceManager.GetString("RemoveMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string RemoveSelectedMod {
            get {
                return ResourceManager.GetString("RemoveSelectedMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string RemoveSubFolderWarning {
            get {
                return ResourceManager.GetString("RemoveSubFolderWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string RemoveVersionConfirmation {
            get {
                return ResourceManager.GetString("RemoveVersionConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string Reselect_Input_Button {
            get {
                return ResourceManager.GetString("Reselect_Input_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string ResetInputMappingsDefaultFormMessage {
            get {
                return ResourceManager.GetString("ResetInputMappingsDefaultFormMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string ResetInputMappingsDefaultFormTitle {
            get {
                return ResourceManager.GetString("ResetInputMappingsDefaultFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string ResetMappingsToDefaultButton {
            get {
                return ResourceManager.GetString("ResetMappingsToDefaultButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string RestoreFailed {
            get {
                return ResourceManager.GetString("RestoreFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string ResultLabel {
            get {
                return ResourceManager.GetString("ResultLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string S3AIRGB {
            get {
                return ResourceManager.GetString("S3AIRGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string S3AIRHomepage {
            get {
                return ResourceManager.GetString("S3AIRHomepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string S3AIRPathNotSet {
            get {
                return ResourceManager.GetString("S3AIRPathNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string S3KROMPathLabel {
            get {
                return ResourceManager.GetString("S3KROMPathLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string Save_Load {
            get {
                return ResourceManager.GetString("Save&Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string SaveInputMappingsButton {
            get {
                return ResourceManager.GetString("SaveInputMappingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string Select_Button {
            get {
                return ResourceManager.GetString("Select_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string SelectFromInstalledVersions {
            get {
                return ResourceManager.GetString("SelectFromInstalledVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string SelectInputTitleExpandable {
            get {
                return ResourceManager.GetString("SelectInputTitleExpandable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string SelectInstallFromAIRZIP {
            get {
                return ResourceManager.GetString("SelectInstallFromAIRZIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string SelectSonic3KRomFile {
            get {
                return ResourceManager.GetString("SelectSonic3KRomFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string SelectSonicAIRVersionZIP {
            get {
                return ResourceManager.GetString("SelectSonicAIRVersionZIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string SetAIRPathFromSettings {
            get {
                return ResourceManager.GetString("SetAIRPathFromSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string SetAIRPathManuallyClassic {
            get {
                return ResourceManager.GetString("SetAIRPathManuallyClassic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string SetCustomGameRecordingFolderTitle {
            get {
                return ResourceManager.GetString("SetCustomGameRecordingFolderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string SetFromInstalledHeader {
            get {
                return ResourceManager.GetString("SetFromInstalledHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string SetManuallyHeader {
            get {
                return ResourceManager.GetString("SetManuallyHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string SettingsTab {
            get {
                return ResourceManager.GetString("SettingsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string SettingsVersionLabel {
            get {
                return ResourceManager.GetString("SettingsVersionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string ShowLogFileButton {
            get {
                return ResourceManager.GetString("ShowLogFileButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string Sonic3AIRPathLabel {
            get {
                return ResourceManager.GetString("Sonic3AIRPathLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string Sonic3KRomFile {
            get {
                return ResourceManager.GetString("Sonic3KRomFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string SonicAIRVersionZIP {
            get {
                return ResourceManager.GetString("SonicAIRVersionZIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string SpecifiedFileDirNotExist {
            get {
                return ResourceManager.GetString("SpecifiedFileDirNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string StartupFailureError {
            get {
                return ResourceManager.GetString("StartupFailureError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string StartupWindowLabel {
            get {
                return ResourceManager.GetString("StartupWindowLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string StayOpenOnExit {
            get {
                return ResourceManager.GetString("StayOpenOnExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string StayOpenOnLoad {
            get {
                return ResourceManager.GetString("StayOpenOnLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string ThumbstickRadioButton {
            get {
                return ResourceManager.GetString("ThumbstickRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string TimestampColumnHeader {
            get {
                return ResourceManager.GetString("TimestampColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string ToolsTab {
            get {
                return ResourceManager.GetString("ToolsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string TryAgain {
            get {
                return ResourceManager.GetString("TryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string TypeGB {
            get {
                return ResourceManager.GetString("TypeGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string UnableToDeleteFile {
            get {
                return ResourceManager.GetString("UnableToDeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string UnableToRemoveVersion {
            get {
                return ResourceManager.GetString("UnableToRemoveVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string UnableToStartS3AIR {
            get {
                return ResourceManager.GetString("UnableToStartS3AIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string UnableToStartS3AIRRecordingViewer {
            get {
                return ResourceManager.GetString("UnableToStartS3AIRRecordingViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string UnableToValididatePath {
            get {
                return ResourceManager.GetString("UnableToValididatePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string UnderstoodButton {
            get {
                return ResourceManager.GetString("UnderstoodButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string UnsetFolderPathString {
            get {
                return ResourceManager.GetString("UnsetFolderPathString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string UpdateAvaliable {
            get {
                return ResourceManager.GetString("UpdateAvaliable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string UpdateFailedError {
            get {
                return ResourceManager.GetString("UpdateFailedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string Updater_Avaliable {
            get {
                return ResourceManager.GetString("Updater_Avaliable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string Updater_UpToDate {
            get {
                return ResourceManager.GetString("Updater_UpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string UpdaterTitle {
            get {
                return ResourceManager.GetString("UpdaterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string UseDarkTheme {
            get {
                return ResourceManager.GetString("UseDarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string UsefulShortKeys {
            get {
                return ResourceManager.GetString("UsefulShortKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string VersionColumnHeader {
            get {
                return ResourceManager.GetString("VersionColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string VersionSelectCaption1 {
            get {
                return ResourceManager.GetString("VersionSelectCaption1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string VersionSelectCaption2 {
            get {
                return ResourceManager.GetString("VersionSelectCaption2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string VersionsTab {
            get {
                return ResourceManager.GetString("VersionsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string Viewer_ActiveModsTab {
            get {
                return ResourceManager.GetString("Viewer_ActiveModsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string Viewer_BaseFolderItemFormatString {
            get {
                return ResourceManager.GetString("Viewer_BaseFolderItemFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string Viewer_ModsTab {
            get {
                return ResourceManager.GetString("Viewer_ModsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string Viewer_SubFolderItemFormatString {
            get {
                return ResourceManager.GetString("Viewer_SubFolderItemFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string WaitingForInputDialogLabel {
            get {
                return ResourceManager.GetString("WaitingForInputDialogLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string WaitingForInputDialogLabelTag {
            get {
                return ResourceManager.GetString("WaitingForInputDialogLabelTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        internal static string Yes_Button {
            get {
                return ResourceManager.GetString("Yes_Button", resourceCulture);
            }
        }
    }
}
