//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sonic3AIR_ModLoader.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class lang_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sonic3AIR_ModLoader.Languages.lang_en", typeof(lang_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string AboutTab {
            get {
                return ResourceManager.GetString("AboutTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a Mod....
        /// </summary>
        internal static string AddAMod {
            get {
                return ResourceManager.GetString("AddAMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the name of the controller as it appears in the system settings or type * to target all devices..
        /// </summary>
        internal static string AddNewDeviceDescription {
            get {
                return ResourceManager.GetString("AddNewDeviceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Device....
        /// </summary>
        internal static string AddNewDeviceTitle {
            get {
                return ResourceManager.GetString("AddNewDeviceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file defined settings does not exist anymore. Launch AIR again outside of the mod loader and try again.
        /// </summary>
        internal static string AIRChangePathNoLongerExists {
            get {
                return ResourceManager.GetString("AIRChangePathNoLongerExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.I.R. Internal Settings.
        /// </summary>
        internal static string AIRInternalSettings {
            get {
                return ResourceManager.GetString("AIRInternalSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.I.R. Media....
        /// </summary>
        internal static string AIRMedia {
            get {
                return ResourceManager.GetString("AIRMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.I.R. Mod Manager Places....
        /// </summary>
        internal static string AIRMMPlaces {
            get {
                return ResourceManager.GetString("AIRMMPlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.I.R. Places....
        /// </summary>
        internal static string AIRPlaces {
            get {
                return ResourceManager.GetString("AIRPlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.I.R. Version.
        /// </summary>
        internal static string AIRVersion {
            get {
                return ResourceManager.GetString("AIRVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for Updates....
        /// </summary>
        internal static string AutoBoot_CheckingForUpdates {
            get {
                return ResourceManager.GetString("AutoBoot_CheckingForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing....
        /// </summary>
        internal static string AutoBoot_Initalizing {
            get {
                return ResourceManager.GetString("AutoBoot_Initalizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launching in.
        /// </summary>
        internal static string AutoBoot_LaunchingIn {
            get {
                return ResourceManager.GetString("AutoBoot_LaunchingIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay (Seconds):.
        /// </summary>
        internal static string AutoBootDelay {
            get {
                return ResourceManager.GetString("AutoBootDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button Mappings.
        /// </summary>
        internal static string ButtonMappings {
            get {
                return ResourceManager.GetString("ButtonMappings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.
        /// </summary>
        internal static string Buttons_A {
            get {
                return ResourceManager.GetString("Buttons_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        internal static string Buttons_B {
            get {
                return ResourceManager.GetString("Buttons_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Buttons_Back {
            get {
                return ResourceManager.GetString("Buttons_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down.
        /// </summary>
        internal static string Buttons_Down {
            get {
                return ResourceManager.GetString("Buttons_Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        internal static string Buttons_Left {
            get {
                return ResourceManager.GetString("Buttons_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        internal static string Buttons_Right {
            get {
                return ResourceManager.GetString("Buttons_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Buttons_Start {
            get {
                return ResourceManager.GetString("Buttons_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up.
        /// </summary>
        internal static string Buttons_Up {
            get {
                return ResourceManager.GetString("Buttons_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        internal static string Buttons_X {
            get {
                return ResourceManager.GetString("Buttons_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y.
        /// </summary>
        internal static string Buttons_Y {
            get {
                return ResourceManager.GetString("Buttons_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By.
        /// </summary>
        internal static string By {
            get {
                return ResourceManager.GetString("By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cancel.
        /// </summary>
        internal static string Cancel_Button {
            get {
                return ResourceManager.GetString("Cancel_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CarJem @ Twitter.
        /// </summary>
        internal static string CarJemTwitter {
            get {
                return ResourceManager.GetString("CarJemTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for A.I.R. Updates on Startup.
        /// </summary>
        internal static string CheckforAIRUpdatesOnStart {
            get {
                return ResourceManager.GetString("CheckforAIRUpdatesOnStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for Game Updates....
        /// </summary>
        internal static string CheckForGameUpdatesExpandable {
            get {
                return ResourceManager.GetString("CheckForGameUpdatesExpandable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following files could not be found: .
        /// </summary>
        internal static string CollectionFilesCouldNotBeFound1 {
            get {
                return ResourceManager.GetString("CollectionFilesCouldNotBeFound1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///If you have not run Sonic 3 A.I.R. yet, please run Sonic 3 A.I.R. once before running the modloader!.
        /// </summary>
        internal static string CollectionFilesCouldNotBeFound2 {
            get {
                return ResourceManager.GetString("CollectionFilesCouldNotBeFound2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///If you have, make sure these locations exist. The modloader can&apos;t run without them.
        /// </summary>
        internal static string CollectionFilesCouldNotBeFound3 {
            get {
                return ResourceManager.GetString("CollectionFilesCouldNotBeFound3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy File Path.
        /// </summary>
        internal static string CopyFilePath {
            get {
                return ResourceManager.GetString("CopyFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease Selected Mod Priority....
        /// </summary>
        internal static string DecreaseModPriority {
            get {
                return ResourceManager.GetString("DecreaseModPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease Selected Mod Priority to Min....
        /// </summary>
        internal static string DecreaseModPriorityToMin {
            get {
                return ResourceManager.GetString("DecreaseModPriorityToMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Device.
        /// </summary>
        internal static string DeleteDeviceTitle {
            get {
                return ResourceManager.GetString("DeleteDeviceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete.
        /// </summary>
        internal static string DeleteItemConfirmation {
            get {
                return ResourceManager.GetString("DeleteItemConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Identifier Names.
        /// </summary>
        internal static string DeviceIdentifierNames {
            get {
                return ResourceManager.GetString("DeviceIdentifierNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading.
        /// </summary>
        internal static string Downloading {
            get {
                return ResourceManager.GetString("Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Auto Boot Mode.
        /// </summary>
        internal static string EnableAutoBootMode {
            get {
                return ResourceManager.GetString("EnableAutoBootMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Mod Stacking.
        /// </summary>
        internal static string EnableModStacking {
            get {
                return ResourceManager.GetString("EnableModStacking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOTE: For A.I.R. Versions.
        /// </summary>
        internal static string EnableModStacking_Note1 {
            get {
                return ResourceManager.GetString("EnableModStacking_Note1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v19.09.19.0 and Above Only.
        /// </summary>
        internal static string EnableModStacking_Note2 {
            get {
                return ResourceManager.GetString("EnableModStacking_Note2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Mod URL....
        /// </summary>
        internal static string EnterModURL {
            get {
                return ResourceManager.GetString("EnterModURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error with loading.
        /// </summary>
        internal static string ErrorWithLoading {
            get {
                return ResourceManager.GetString("ErrorWithLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eukaryot3K @ Twitter.
        /// </summary>
        internal static string Eukaryot3KTwitter {
            get {
                return ResourceManager.GetString("Eukaryot3KTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail Safe Mode.
        /// </summary>
        internal static string FailSafeMode {
            get {
                return ResourceManager.GetString("FailSafeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix Glitches.
        /// </summary>
        internal static string FixGlitches {
            get {
                return ResourceManager.GetString("FixGlitches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force Start.
        /// </summary>
        internal static string ForceStart {
            get {
                return ResourceManager.GetString("ForceStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gamebanana URL Handler Options....
        /// </summary>
        internal static string GameBannaURLHandler {
            get {
                return ResourceManager.GetString("GameBannaURLHandler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game has been installed at.
        /// </summary>
        internal static string GameInstalledAt {
            get {
                return ResourceManager.GetString("GameInstalledAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string GeneralTab {
            get {
                return ResourceManager.GetString("GeneralTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guides/Shortcuts.
        /// </summary>
        internal static string GuidesTab {
            get {
                return ResourceManager.GetString("GuidesTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase Selected Mod Priority....
        /// </summary>
        internal static string IncreaseModPriority {
            get {
                return ResourceManager.GetString("IncreaseModPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase Selected Mod Priority to Max....
        /// </summary>
        internal static string IncreaseModPriorityToMax {
            get {
                return ResourceManager.GetString("IncreaseModPriorityToMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [INPUT].
        /// </summary>
        internal static string Input_INPUT {
            get {
                return ResourceManager.GetString("Input_INPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [MULTI].
        /// </summary>
        internal static string Input_MULTI {
            get {
                return ResourceManager.GetString("Input_MULTI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [NONE].
        /// </summary>
        internal static string Input_NONE {
            get {
                return ResourceManager.GetString("Input_NONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [NULL].
        /// </summary>
        internal static string Input_NULL {
            get {
                return ResourceManager.GetString("Input_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [UNSUPPORTED].
        /// </summary>
        internal static string Input_UNSUPPORTED {
            get {
                return ResourceManager.GetString("Input_UNSUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Loading Input Configuration File!
        ///Make sure your game is up to date and you have A.I.R.&apos;s Game Path set in Options.
        ///.
        /// </summary>
        internal static string InputMappingError1 {
            get {
                return ResourceManager.GetString("InputMappingError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error reading the config file in this Version&apos;s Folder!
        /// Please make sure nothing is wrong with it or do a clean install of this version of A.I.R..
        /// </summary>
        internal static string InputMappingError2 {
            get {
                return ResourceManager.GetString("InputMappingError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The config file does not exist in the A.I.R. EXE Folder.
        /// Please make sure the file exists or do a clean install of this version of A.I.R..
        /// </summary>
        internal static string InputMappingError3 {
            get {
                return ResourceManager.GetString("InputMappingError3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        internal static string InputTab {
            get {
                return ResourceManager.GetString("InputTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed Versions.
        /// </summary>
        internal static string InstalledVersions {
            get {
                return ResourceManager.GetString("InstalledVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid URL.
        /// </summary>
        internal static string InvalidURL {
            get {
                return ResourceManager.GetString("InvalidURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Likely a JSON Error; Make sure the mod.json file is formated correctly!).
        /// </summary>
        internal static string JSONErrorPossible {
            get {
                return ResourceManager.GetString("JSONErrorPossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log file not found.
        /// </summary>
        internal static string LogFileNotFound {
            get {
                return ResourceManager.GetString("LogFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod Manager Options.
        /// </summary>
        internal static string ModManagerOptions {
            get {
                return ResourceManager.GetString("ModManagerOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod Manager Version.
        /// </summary>
        internal static string ModManagerVersion {
            get {
                return ResourceManager.GetString("ModManagerVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mods.
        /// </summary>
        internal static string ModsTab {
            get {
                return ResourceManager.GetString("ModsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod Properties.
        /// </summary>
        internal static string ModsTab_ModProperties {
            get {
                return ResourceManager.GetString("ModsTab_ModProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More....
        /// </summary>
        internal static string MoreExpandable {
            get {
                return ResourceManager.GetString("MoreExpandable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Installed Versions.
        /// </summary>
        internal static string NoInstalledVersions {
            get {
                return ResourceManager.GetString("NoInstalledVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;OK.
        /// </summary>
        internal static string Ok_Button {
            get {
                return ResourceManager.GetString("Ok_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open AppData Folder.
        /// </summary>
        internal static string OpenAppDataFolder {
            get {
                return ResourceManager.GetString("OpenAppDataFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Config File.
        /// </summary>
        internal static string OpenConfigFile {
            get {
                return ResourceManager.GetString("OpenConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Downloads Folder.
        /// </summary>
        internal static string OpenDownloadsFolder {
            get {
                return ResourceManager.GetString("OpenDownloadsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open EXE Folder.
        /// </summary>
        internal static string OpenEXEFolder {
            get {
                return ResourceManager.GetString("OpenEXEFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Location....
        /// </summary>
        internal static string OpenLocationExpandable {
            get {
                return ResourceManager.GetString("OpenLocationExpandable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Mod Folder.
        /// </summary>
        internal static string OpenModFolder {
            get {
                return ResourceManager.GetString("OpenModFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonic 3 A.I.R. Modding Instructions.
        /// </summary>
        internal static string OpenModInstructions {
            get {
                return ResourceManager.GetString("OpenModInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Mods Folder.
        /// </summary>
        internal static string OpenModsFolder {
            get {
                return ResourceManager.GetString("OpenModsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Modding Templates Folder.
        /// </summary>
        internal static string OpenModTemplatesFolder {
            get {
                return ResourceManager.GetString("OpenModTemplatesFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Mod URL.
        /// </summary>
        internal static string OpenModURL {
            get {
                return ResourceManager.GetString("OpenModURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Sample Mods Folder.
        /// </summary>
        internal static string OpenSampleModsFolder {
            get {
                return ResourceManager.GetString("OpenSampleModsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Settings File.
        /// </summary>
        internal static string OpenSettingsFile {
            get {
                return ResourceManager.GetString("OpenSettingsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open System Settings....
        /// </summary>
        internal static string OpenSystemSettingsExpandable {
            get {
                return ResourceManager.GetString("OpenSystemSettingsExpandable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonic 3 A.I.R. User Manual.
        /// </summary>
        internal static string OpenUserManual {
            get {
                return ResourceManager.GetString("OpenUserManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Versions Folder.
        /// </summary>
        internal static string OpenVersionsFolder {
            get {
                return ResourceManager.GetString("OpenVersionsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Refresh the Mod List!.
        /// </summary>
        internal static string PleaseRefreshTheModList {
            get {
                return ResourceManager.GetString("PleaseRefreshTheModList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        internal static string Reason {
            get {
                return ResourceManager.GetString("Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording File Path Copied to Clipboard!.
        /// </summary>
        internal static string RecordingPathCopiedToClipboard {
            get {
                return ResourceManager.GetString("RecordingPathCopiedToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Recordings.
        /// </summary>
        internal static string RecordingsTab {
            get {
                return ResourceManager.GetString("RecordingsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Uploaded to File.io, it will expire in 1 week and has a one time use:.
        /// </summary>
        internal static string RecordingUploaded1 {
            get {
                return ResourceManager.GetString("RecordingUploaded1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (URL Has Been Copied to Clipboard):.
        /// </summary>
        internal static string RecordingUploaded2 {
            get {
                return ResourceManager.GetString("RecordingUploaded2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        internal static string Reload {
            get {
                return ResourceManager.GetString("Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification: Do you want to remove.
        /// </summary>
        internal static string RemoveInputDeviceConfirmation1 {
            get {
                return ResourceManager.GetString("RemoveInputDeviceConfirmation1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from the list of acceptable devices for this input?.
        /// </summary>
        internal static string RemoveInputDeviceConfirmation2 {
            get {
                return ResourceManager.GetString("RemoveInputDeviceConfirmation2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Mod.
        /// </summary>
        internal static string RemoveMod {
            get {
                return ResourceManager.GetString("RemoveMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Selected Mod....
        /// </summary>
        internal static string RemoveSelectedMod {
            get {
                return ResourceManager.GetString("RemoveSelectedMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove Version.
        /// </summary>
        internal static string RemoveVersionConfirmation {
            get {
                return ResourceManager.GetString("RemoveVersionConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3AIR @ Gamebanana.
        /// </summary>
        internal static string S3AIRGB {
            get {
                return ResourceManager.GetString("S3AIRGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonic 3 A.I.R. Homepage.
        /// </summary>
        internal static string S3AIRHomepage {
            get {
                return ResourceManager.GetString("S3AIRHomepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonic 3 A.I.R.&apos;s Path is not set!.
        /// </summary>
        internal static string S3AIRPathNotSet {
            get {
                return ResourceManager.GetString("S3AIRPathNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonic 3K ROM Path:.
        /// </summary>
        internal static string S3KROMPathLabel {
            get {
                return ResourceManager.GetString("S3KROMPathLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save &amp; Load.
        /// </summary>
        internal static string Save_Load {
            get {
                return ResourceManager.GetString("Save&Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select from Installed A.I.R. Versions....
        /// </summary>
        internal static string SelectFromInstalledVersions {
            get {
                return ResourceManager.GetString("SelectFromInstalledVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select/Install from A.I.R. Version ZIP....
        /// </summary>
        internal static string SelectInstallFromAIRZIP {
            get {
                return ResourceManager.GetString("SelectInstallFromAIRZIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Sonic 3K ROM File....
        /// </summary>
        internal static string SelectSonic3KRomFile {
            get {
                return ResourceManager.GetString("SelectSonic3KRomFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Sonic 3 A.I.R. Version ZIP....
        /// </summary>
        internal static string SelectSonicAIRVersionZIP {
            get {
                return ResourceManager.GetString("SelectSonicAIRVersionZIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set A.I.R. Path from Settings File....
        /// </summary>
        internal static string SetAIRPathFromSettings {
            get {
                return ResourceManager.GetString("SetAIRPathFromSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set A.I.R. Path Manually (Classic)....
        /// </summary>
        internal static string SetAIRPathManuallyClassic {
            get {
                return ResourceManager.GetString("SetAIRPathManuallyClassic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get/Set from Installed Versions:.
        /// </summary>
        internal static string SetFromInstalledHeader {
            get {
                return ResourceManager.GetString("SetFromInstalledHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Manually:.
        /// </summary>
        internal static string SetManuallyHeader {
            get {
                return ResourceManager.GetString("SetManuallyHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsTab {
            get {
                return ResourceManager.GetString("SettingsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonic 3 A.I.R. Path:.
        /// </summary>
        internal static string Sonic3AIRPathLabel {
            get {
                return ResourceManager.GetString("Sonic3AIRPathLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonic 3K ROM File.
        /// </summary>
        internal static string Sonic3KRomFile {
            get {
                return ResourceManager.GetString("Sonic3KRomFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonic 3 A.I.R. Version ZIP.
        /// </summary>
        internal static string SonicAIRVersionZIP {
            get {
                return ResourceManager.GetString("SonicAIRVersionZIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified file or directory does not exist!.
        /// </summary>
        internal static string SpecifiedFileDirNotExist {
            get {
                return ResourceManager.GetString("SpecifiedFileDirNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stay Open on Game Exit.
        /// </summary>
        internal static string StayOpenOnExit {
            get {
                return ResourceManager.GetString("StayOpenOnExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stay Open on Game Load.
        /// </summary>
        internal static string StayOpenOnLoad {
            get {
                return ResourceManager.GetString("StayOpenOnLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        internal static string ToolsTab {
            get {
                return ResourceManager.GetString("ToolsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to Delete File!.
        /// </summary>
        internal static string UnableToDeleteFile {
            get {
                return ResourceManager.GetString("UnableToDeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to Remove Version!.
        /// </summary>
        internal static string UnableToRemoveVersion {
            get {
                return ResourceManager.GetString("UnableToRemoveVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to Validate Path.
        /// </summary>
        internal static string UnableToValididatePath {
            get {
                return ResourceManager.GetString("UnableToValididatePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Useful In-Game Shortcuts/Keys:
        ///
        ///Alt + Enter - Toggle Fullscreen
        ///F2 - Take a Game Recording Capture
        ///Right Click - Open A.I.R Context Menu
        ///F3 - Rescan for Game Controllers
        ///F4 - Switches Game Controllers for P1 and P2
        ///Numpad Plus/Minus - Adjust Global Audio Volume
        ///Alt + B - Change Background Blur
        ///Alt + F - Change Filter
        ///Alt + P - Show Performance Display.
        /// </summary>
        internal static string UsefulShortKeys {
            get {
                return ResourceManager.GetString("UsefulShortKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versions.
        /// </summary>
        internal static string VersionsTab {
            get {
                return ResourceManager.GetString("VersionsTab", resourceCulture);
            }
        }
    }
}
