//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sonic3AIR_ModLoader.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class lang_gr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang_gr() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sonic3AIR_ModLoader.Languages.lang_gr", typeof(lang_gr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Über.
        /// </summary>
        internal static string AboutTab {
            get {
                return ResourceManager.GetString("AboutTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod hinzufügen....
        /// </summary>
        internal static string AddAMod {
            get {
                return ResourceManager.GetString("AddAMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trage den Namen des Game Controllers ein, wie er in den Systemeinstellungen aufgeführt wird, oder * für alle Geräte..
        /// </summary>
        internal static string AddNewDeviceDescription {
            get {
                return ResourceManager.GetString("AddNewDeviceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neues Gerät hinzufügen.
        /// </summary>
        internal static string AddNewDeviceTitle {
            get {
                return ResourceManager.GetString("AddNewDeviceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pfad nicht gesetzt. Kann Sonic 3 A.I.R. nicht starten!.
        /// </summary>
        internal static string AIRCanNotStartNoPath {
            get {
                return ResourceManager.GetString("AIRCanNotStartNoPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Datei mit deinen Spieleinstellungen existiert nicht mehr. Starte Sonic 3 A.I.R. einmal ohne den Mod Loader und evrsuche es dann noch einmal..
        /// </summary>
        internal static string AIRChangePathNoLongerExists {
            get {
                return ResourceManager.GetString("AIRChangePathNoLongerExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.I.R. interne Einstellungen.
        /// </summary>
        internal static string AIRInternalSettings {
            get {
                return ResourceManager.GetString("AIRInternalSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.I.R. Medien....
        /// </summary>
        internal static string AIRMedia {
            get {
                return ResourceManager.GetString("AIRMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.I.R. Mod Manager Orte....
        /// </summary>
        internal static string AIRMMPlaces {
            get {
                return ResourceManager.GetString("AIRMMPlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.I.R. Orte....
        /// </summary>
        internal static string AIRPlaces {
            get {
                return ResourceManager.GetString("AIRPlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.I.R. Version.
        /// </summary>
        internal static string AIRVersion {
            get {
                return ResourceManager.GetString("AIRVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suche nach Updates....
        /// </summary>
        internal static string AutoBoot_CheckingForUpdates {
            get {
                return ResourceManager.GetString("AutoBoot_CheckingForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialisiere....
        /// </summary>
        internal static string AutoBoot_Initalizing {
            get {
                return ResourceManager.GetString("AutoBoot_Initalizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starte in.
        /// </summary>
        internal static string AutoBoot_LaunchingIn {
            get {
                return ResourceManager.GetString("AutoBoot_LaunchingIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verzögerung (Sekunden):.
        /// </summary>
        internal static string AutoBootDelay {
            get {
                return ResourceManager.GetString("AutoBootDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achse/POV:.
        /// </summary>
        internal static string AxisPOVLabel {
            get {
                return ResourceManager.GetString("AxisPOVLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achse.
        /// </summary>
        internal static string AxisRadioButton {
            get {
                return ResourceManager.GetString("AxisRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knopf:.
        /// </summary>
        internal static string ButtonLabel {
            get {
                return ResourceManager.GetString("ButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tastenzuordnungen.
        /// </summary>
        internal static string ButtonMappings {
            get {
                return ResourceManager.GetString("ButtonMappings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.
        /// </summary>
        internal static string Buttons_A {
            get {
                return ResourceManager.GetString("Buttons_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        internal static string Buttons_B {
            get {
                return ResourceManager.GetString("Buttons_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zurück.
        /// </summary>
        internal static string Buttons_Back {
            get {
                return ResourceManager.GetString("Buttons_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unten.
        /// </summary>
        internal static string Buttons_Down {
            get {
                return ResourceManager.GetString("Buttons_Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links.
        /// </summary>
        internal static string Buttons_Left {
            get {
                return ResourceManager.GetString("Buttons_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechts.
        /// </summary>
        internal static string Buttons_Right {
            get {
                return ResourceManager.GetString("Buttons_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Buttons_Start {
            get {
                return ResourceManager.GetString("Buttons_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oben.
        /// </summary>
        internal static string Buttons_Up {
            get {
                return ResourceManager.GetString("Buttons_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        internal static string Buttons_X {
            get {
                return ResourceManager.GetString("Buttons_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y.
        /// </summary>
        internal static string Buttons_Y {
            get {
                return ResourceManager.GetString("Buttons_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Von.
        /// </summary>
        internal static string By {
            get {
                return ResourceManager.GetString("By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbrechen.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Abbrechen.
        /// </summary>
        internal static string Cancel_Button {
            get {
                return ResourceManager.GetString("Cancel_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CarJem @ Twitter.
        /// </summary>
        internal static string CarJemTwitter {
            get {
                return ResourceManager.GetString("CarJemTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beim Start auf A.I.R. Updates prüfen.
        /// </summary>
        internal static string CheckforAIRUpdatesOnStart {
            get {
                return ResourceManager.GetString("CheckforAIRUpdatesOnStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auf Spiel-Updates prüfen....
        /// </summary>
        internal static string CheckForGameUpdatesExpandable {
            get {
                return ResourceManager.GetString("CheckForGameUpdatesExpandable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folgende Dateien konnten nicht gefunden werden:.
        /// </summary>
        internal static string CollectionFilesCouldNotBeFound1 {
            get {
                return ResourceManager.GetString("CollectionFilesCouldNotBeFound1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falls du Sonic 3 A.I.R. noch nicht zuvor gestartet hast, starte es einmal bevor du den Mod Loader öffnest!.
        /// </summary>
        internal static string CollectionFilesCouldNotBeFound2 {
            get {
                return ResourceManager.GetString("CollectionFilesCouldNotBeFound2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falls du das bereits getan hast, stelle sicher, dass diese Orte existieren. Der Mod Loader kann ohne sie nicht laufen..
        /// </summary>
        internal static string CollectionFilesCouldNotBeFound3 {
            get {
                return ResourceManager.GetString("CollectionFilesCouldNotBeFound3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller.
        /// </summary>
        internal static string ControllerRadioButton {
            get {
                return ResourceManager.GetString("ControllerRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dateipfad kopieren.
        /// </summary>
        internal static string CopyFilePath {
            get {
                return ResourceManager.GetString("CopyFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzerdefiniert/Erweitert:.
        /// </summary>
        internal static string CustomAdvancedLabel {
            get {
                return ResourceManager.GetString("CustomAdvancedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eigener String:.
        /// </summary>
        internal static string CustomStringLabel {
            get {
                return ResourceManager.GetString("CustomStringLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priorität der ausgewählten Mod verringern....
        /// </summary>
        internal static string DecreaseModPriority {
            get {
                return ResourceManager.GetString("DecreaseModPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priorität der ausgewählten Mod auf Minimum....
        /// </summary>
        internal static string DecreaseModPriorityToMin {
            get {
                return ResourceManager.GetString("DecreaseModPriorityToMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Löschen.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerät entfernen.
        /// </summary>
        internal static string DeleteDeviceTitle {
            get {
                return ResourceManager.GetString("DeleteDeviceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Willst du folgendes wirklich löschen.
        /// </summary>
        internal static string DeleteItemConfirmation {
            get {
                return ResourceManager.GetString("DeleteItemConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zuordnung löschen.
        /// </summary>
        internal static string DeleteKeybindTitle {
            get {
                return ResourceManager.GetString("DeleteKeybindTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sicherheitsabfrage: Willst du die Tastenzuordnung.
        /// </summary>
        internal static string DeleteKeybindVerification1 {
            get {
                return ResourceManager.GetString("DeleteKeybindVerification1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to löschen?.
        /// </summary>
        internal static string DeleteKeybindVerification2 {
            get {
                return ResourceManager.GetString("DeleteKeybindVerification2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerätebezeichner.
        /// </summary>
        internal static string DeviceIdentifierNames {
            get {
                return ResourceManager.GetString("DeviceIdentifierNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Richtung.
        /// </summary>
        internal static string DirectionGB {
            get {
                return ResourceManager.GetString("DirectionGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wird heruntergeladen.
        /// </summary>
        internal static string Downloading {
            get {
                return ResourceManager.GetString("Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bearbeiten....
        /// </summary>
        internal static string EditExpandable {
            get {
                return ResourceManager.GetString("EditExpandable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tastenzuordnungen bearbeiten....
        /// </summary>
        internal static string EditKeybindingsTitleExpandable {
            get {
                return ResourceManager.GetString("EditKeybindingsTitleExpandable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatischen Start einschalten.
        /// </summary>
        internal static string EnableAutoBootMode {
            get {
                return ResourceManager.GetString("EnableAutoBootMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stapeln mehrerer Mods aktivieren.
        /// </summary>
        internal static string EnableModStacking {
            get {
                return ResourceManager.GetString("EnableModStacking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HINWEIS: Nur für A.I.R. Versionen.
        /// </summary>
        internal static string EnableModStacking_Note1 {
            get {
                return ResourceManager.GetString("EnableModStacking_Note1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v19.09.19.0 und darüber.
        /// </summary>
        internal static string EnableModStacking_Note2 {
            get {
                return ResourceManager.GetString("EnableModStacking_Note2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod URL hinzufügen....
        /// </summary>
        internal static string EnterModURL {
            get {
                return ResourceManager.GetString("EnterModURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim Laden.
        /// </summary>
        internal static string ErrorWithLoading {
            get {
                return ResourceManager.GetString("ErrorWithLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eukaryot3K @ Twitter.
        /// </summary>
        internal static string Eukaryot3KTwitter {
            get {
                return ResourceManager.GetString("Eukaryot3KTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anwendungsdatei.
        /// </summary>
        internal static string EXEFileDialogFilter {
            get {
                return ResourceManager.GetString("EXEFileDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonic 3 A.I.R. Anwendungsdatei wählen....
        /// </summary>
        internal static string EXEFileDialogTitle {
            get {
                return ResourceManager.GetString("EXEFileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beenden.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abgesicherter Modus.
        /// </summary>
        internal static string FailSafeMode {
            get {
                return ResourceManager.GetString("FailSafeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glitches beheben.
        /// </summary>
        internal static string FixGlitches {
            get {
                return ResourceManager.GetString("FixGlitches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start erzwingen.
        /// </summary>
        internal static string ForceStart {
            get {
                return ResourceManager.GetString("ForceStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gamebanana URL Handler Einstellungen....
        /// </summary>
        internal static string GameBannaURLHandler {
            get {
                return ResourceManager.GetString("GameBannaURLHandler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Spiel wurde installiert nach.
        /// </summary>
        internal static string GameInstalledAt {
            get {
                return ResourceManager.GetString("GameInstalledAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allgemein.
        /// </summary>
        internal static string GeneralTab {
            get {
                return ResourceManager.GetString("GeneralTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anleitungen/Links.
        /// </summary>
        internal static string GuidesTab {
            get {
                return ResourceManager.GetString("GuidesTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID:.
        /// </summary>
        internal static string IDLabel {
            get {
                return ResourceManager.GetString("IDLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priorität der ausgewählten Mod erhöhen....
        /// </summary>
        internal static string IncreaseModPriority {
            get {
                return ResourceManager.GetString("IncreaseModPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priorität der ausgewählten Mod auf Maximum....
        /// </summary>
        internal static string IncreaseModPriorityToMax {
            get {
                return ResourceManager.GetString("IncreaseModPriorityToMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [EINGABE].
        /// </summary>
        internal static string Input_INPUT {
            get {
                return ResourceManager.GetString("Input_INPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [MEHRERE].
        /// </summary>
        internal static string Input_MULTI {
            get {
                return ResourceManager.GetString("Input_MULTI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [KEINE].
        /// </summary>
        internal static string Input_NONE {
            get {
                return ResourceManager.GetString("Input_NONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [NULL].
        /// </summary>
        internal static string Input_NULL {
            get {
                return ResourceManager.GetString("Input_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [NICHT UNTERSTÜTZT].
        /// </summary>
        internal static string Input_UNSUPPORTED {
            get {
                return ResourceManager.GetString("Input_UNSUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim Laden der Config-Datei!
        ///Stelle sicher, dass das Spiel auf dem aktuellsten Stand ist und du A.I.R.&apos;s Installationspfad in den EInstellungen eingetragen hast..
        /// </summary>
        internal static string InputMappingError1 {
            get {
                return ResourceManager.GetString("InputMappingError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim Laden der Config-Datei im Ordner dieser Version!
        ///Bitte stelle sicher, dass die Config-Datei in Ordnung ist, oder installiere A.I.R. neu..
        /// </summary>
        internal static string InputMappingError2 {
            get {
                return ResourceManager.GetString("InputMappingError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Config-Datei existiert nicht im Installations-Ordner.
        ///Bitte stelle sicher, dass sie existiert, oder installiere A.I.R. neu..
        /// </summary>
        internal static string InputMappingError3 {
            get {
                return ResourceManager.GetString("InputMappingError3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eingabe.
        /// </summary>
        internal static string InputTab {
            get {
                return ResourceManager.GetString("InputTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installierte Versionen.
        /// </summary>
        internal static string InstalledVersions {
            get {
                return ResourceManager.GetString("InstalledVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungültige URL.
        /// </summary>
        internal static string InvalidURL {
            get {
                return ResourceManager.GetString("InvalidURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Wahrscheinlich ein JSON Fehler; stelle sicher dass die mod.json Datei richtig formatiert ist!).
        /// </summary>
        internal static string JSONErrorPossible {
            get {
                return ResourceManager.GetString("JSONErrorPossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Existiert).
        /// </summary>
        internal static string KeybindingsExistingNote {
            get {
                return ResourceManager.GetString("KeybindingsExistingNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tastenzuordnungen:.
        /// </summary>
        internal static string KeybindingsLabel {
            get {
                return ResourceManager.GetString("KeybindingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tastatur.
        /// </summary>
        internal static string KeyboardRadioButton {
            get {
                return ResourceManager.GetString("KeyboardRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taste:.
        /// </summary>
        internal static string KeyLabel {
            get {
                return ResourceManager.GetString("KeyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprache:.
        /// </summary>
        internal static string LanguageLabel {
            get {
                return ResourceManager.GetString("LanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log-Datei nicht gefunden.
        /// </summary>
        internal static string LogFileNotFound {
            get {
                return ResourceManager.GetString("LogFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonic 3 A.I.R.&apos;s Dateipfad ist nicht gesetzt, willst du ihn jetzt festlegen?.
        /// </summary>
        internal static string MissingAIRSetNowAlert {
            get {
                return ResourceManager.GetString("MissingAIRSetNowAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonic 3 AIR Mod.
        /// </summary>
        internal static string ModFileDialogFilter {
            get {
                return ResourceManager.GetString("ModFileDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komprimierte Mod-Datei wählen....
        /// </summary>
        internal static string ModFileDialogTitle {
            get {
                return ResourceManager.GetString("ModFileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod Manager Optionen.
        /// </summary>
        internal static string ModManagerOptions {
            get {
                return ResourceManager.GetString("ModManagerOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod Manager Version.
        /// </summary>
        internal static string ModManagerVersion {
            get {
                return ResourceManager.GetString("ModManagerVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mods.
        /// </summary>
        internal static string ModsTab {
            get {
                return ResourceManager.GetString("ModsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod-Eigenschaften.
        /// </summary>
        internal static string ModsTab_ModProperties {
            get {
                return ResourceManager.GetString("ModsTab_ModProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mehr....
        /// </summary>
        internal static string MoreExpandable {
            get {
                return ResourceManager.GetString("MoreExpandable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nein.
        /// </summary>
        internal static string No_Button {
            get {
                return ResourceManager.GetString("No_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine Versionen installiert.
        /// </summary>
        internal static string NoInstalledVersions {
            get {
                return ResourceManager.GetString("NoInstalledVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine Beschreibung angegeben..
        /// </summary>
        internal static string NoModDescript {
            get {
                return ResourceManager.GetString("NoModDescript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Ok.
        /// </summary>
        internal static string Ok_Button {
            get {
                return ResourceManager.GetString("Ok_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öffnen.
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppData Ordner öffnen.
        /// </summary>
        internal static string OpenAppDataFolder {
            get {
                return ResourceManager.GetString("OpenAppDataFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config Datei öffnen.
        /// </summary>
        internal static string OpenConfigFile {
            get {
                return ResourceManager.GetString("OpenConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaders Ordner öffnen.
        /// </summary>
        internal static string OpenDownloadsFolder {
            get {
                return ResourceManager.GetString("OpenDownloadsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spiel-EXE Ordner öffnen.
        /// </summary>
        internal static string OpenEXEFolder {
            get {
                return ResourceManager.GetString("OpenEXEFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordner öffnen....
        /// </summary>
        internal static string OpenLocationExpandable {
            get {
                return ResourceManager.GetString("OpenLocationExpandable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod-Ordner öffnen.
        /// </summary>
        internal static string OpenModFolder {
            get {
                return ResourceManager.GetString("OpenModFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonic 3 A.I.R. Modding-Anleitung.
        /// </summary>
        internal static string OpenModInstructions {
            get {
                return ResourceManager.GetString("OpenModInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod-Ordner öffnen.
        /// </summary>
        internal static string OpenModsFolder {
            get {
                return ResourceManager.GetString("OpenModsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod-Vorlagenordner öffnen.
        /// </summary>
        internal static string OpenModTemplatesFolder {
            get {
                return ResourceManager.GetString("OpenModTemplatesFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod URL öffnen.
        /// </summary>
        internal static string OpenModURL {
            get {
                return ResourceManager.GetString("OpenModURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beispiel-Mods öffnen.
        /// </summary>
        internal static string OpenSampleModsFolder {
            get {
                return ResourceManager.GetString("OpenSampleModsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datei mit Spieleinstellungen öffnen.
        /// </summary>
        internal static string OpenSettingsFile {
            get {
                return ResourceManager.GetString("OpenSettingsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Systemeinstellungen öffnen....
        /// </summary>
        internal static string OpenSystemSettingsExpandable {
            get {
                return ResourceManager.GetString("OpenSystemSettingsExpandable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonic 3 A.I.R. Handbuch.
        /// </summary>
        internal static string OpenUserManual {
            get {
                return ResourceManager.GetString("OpenUserManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versions-Ordner öffnen.
        /// </summary>
        internal static string OpenVersionsFolder {
            get {
                return ResourceManager.GetString("OpenVersionsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte aktualisiere die Mod-Liste!.
        /// </summary>
        internal static string PleaseRefreshTheModList {
            get {
                return ResourceManager.GetString("PleaseRefreshTheModList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POV.
        /// </summary>
        internal static string POVRadioButton {
            get {
                return ResourceManager.GetString("POVRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grund.
        /// </summary>
        internal static string Reason {
            get {
                return ResourceManager.GetString("Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording-Dateipfad in die Zwischenablage kopiert!.
        /// </summary>
        internal static string RecordingPathCopiedToClipboard {
            get {
                return ResourceManager.GetString("RecordingPathCopiedToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aufzeichnungen.
        /// </summary>
        internal static string RecordingsTab {
            get {
                return ResourceManager.GetString("RecordingsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datei hochgeladen zu File.io, es ist dort eine Woche gültig und einmalig nutzbar:.
        /// </summary>
        internal static string RecordingUploaded1 {
            get {
                return ResourceManager.GetString("RecordingUploaded1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (URL wurde in die Zwischenablage kopiert).
        /// </summary>
        internal static string RecordingUploaded2 {
            get {
                return ResourceManager.GetString("RecordingUploaded2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktualisieren.
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neu laden.
        /// </summary>
        internal static string Reload {
            get {
                return ResourceManager.GetString("Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entfernen.
        /// </summary>
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sicherheitsabfrage: Willst du.
        /// </summary>
        internal static string RemoveInputDeviceConfirmation1 {
            get {
                return ResourceManager.GetString("RemoveInputDeviceConfirmation1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to von der Liste der verfügbaren Eingabegeräte löschen?.
        /// </summary>
        internal static string RemoveInputDeviceConfirmation2 {
            get {
                return ResourceManager.GetString("RemoveInputDeviceConfirmation2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod entfernen.
        /// </summary>
        internal static string RemoveMod {
            get {
                return ResourceManager.GetString("RemoveMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ausgewählte Mod entfernen....
        /// </summary>
        internal static string RemoveSelectedMod {
            get {
                return ResourceManager.GetString("RemoveSelectedMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Willst du die folgende Version wirklich entfernen.
        /// </summary>
        internal static string RemoveVersionConfirmation {
            get {
                return ResourceManager.GetString("RemoveVersionConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ergebnis:.
        /// </summary>
        internal static string ResultLabel {
            get {
                return ResourceManager.GetString("ResultLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3AIR @ Gamebanana.
        /// </summary>
        internal static string S3AIRGB {
            get {
                return ResourceManager.GetString("S3AIRGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonic 3 A.I.R. Homepage.
        /// </summary>
        internal static string S3AIRHomepage {
            get {
                return ResourceManager.GetString("S3AIRHomepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Pfad zu Sonic 3 A.I.R. ist nicht gesetzt!.
        /// </summary>
        internal static string S3AIRPathNotSet {
            get {
                return ResourceManager.GetString("S3AIRPathNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonic 3K ROM Pfad:.
        /// </summary>
        internal static string S3KROMPathLabel {
            get {
                return ResourceManager.GetString("S3KROMPathLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichern.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichern &amp; Starten.
        /// </summary>
        internal static string Save_Load {
            get {
                return ResourceManager.GetString("Save&Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aus installierten A.I.R. Versionen wählen....
        /// </summary>
        internal static string SelectFromInstalledVersions {
            get {
                return ResourceManager.GetString("SelectFromInstalledVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eingabe wählen....
        /// </summary>
        internal static string SelectInputTitleExpandable {
            get {
                return ResourceManager.GetString("SelectInputTitleExpandable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aus A.I.R. Version ZIP installieren und auswählen....
        /// </summary>
        internal static string SelectInstallFromAIRZIP {
            get {
                return ResourceManager.GetString("SelectInstallFromAIRZIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonic 3K ROM Datei wählen....
        /// </summary>
        internal static string SelectSonic3KRomFile {
            get {
                return ResourceManager.GetString("SelectSonic3KRomFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonic 3 A.I.R. Versions ZIP wählen....
        /// </summary>
        internal static string SelectSonicAIRVersionZIP {
            get {
                return ResourceManager.GetString("SelectSonicAIRVersionZIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.I.R. Pfad aus Spieleinstellungen auslesen....
        /// </summary>
        internal static string SetAIRPathFromSettings {
            get {
                return ResourceManager.GetString("SetAIRPathFromSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.I.R. Pfad manuell setzen (klassisch)....
        /// </summary>
        internal static string SetAIRPathManuallyClassic {
            get {
                return ResourceManager.GetString("SetAIRPathManuallyClassic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aus installierten Versionen holen/setzen.
        /// </summary>
        internal static string SetFromInstalledHeader {
            get {
                return ResourceManager.GetString("SetFromInstalledHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manuell setzen:.
        /// </summary>
        internal static string SetManuallyHeader {
            get {
                return ResourceManager.GetString("SetManuallyHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einstellungen.
        /// </summary>
        internal static string SettingsTab {
            get {
                return ResourceManager.GetString("SettingsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonic 3 A.I.R. Installationspfad:.
        /// </summary>
        internal static string Sonic3AIRPathLabel {
            get {
                return ResourceManager.GetString("Sonic3AIRPathLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonic 3K ROM Datei.
        /// </summary>
        internal static string Sonic3KRomFile {
            get {
                return ResourceManager.GetString("Sonic3KRomFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonic 3 A.I.R. Versions ZIP.
        /// </summary>
        internal static string SonicAIRVersionZIP {
            get {
                return ResourceManager.GetString("SonicAIRVersionZIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die angegebene Datei oder Verzeichnis existiert nicht!.
        /// </summary>
        internal static string SpecifiedFileDirNotExist {
            get {
                return ResourceManager.GetString("SpecifiedFileDirNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deine Sonic 3 A.I.R. Version ist veraltet, bitte update auf Version 19.08.17.0 oder höher! (und starte es zumindest einmal).
        /// </summary>
        internal static string StartupFailureError {
            get {
                return ResourceManager.GetString("StartupFailureError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nach Spielende offen bleiben.
        /// </summary>
        internal static string StayOpenOnExit {
            get {
                return ResourceManager.GetString("StayOpenOnExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nach Spielstart offen bleiben.
        /// </summary>
        internal static string StayOpenOnLoad {
            get {
                return ResourceManager.GetString("StayOpenOnLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analogstick.
        /// </summary>
        internal static string ThumbstickRadioButton {
            get {
                return ResourceManager.GetString("ThumbstickRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Werkzeuge.
        /// </summary>
        internal static string ToolsTab {
            get {
                return ResourceManager.GetString("ToolsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ.
        /// </summary>
        internal static string TypeGB {
            get {
                return ResourceManager.GetString("TypeGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kann Datei nicht löschen!.
        /// </summary>
        internal static string UnableToDeleteFile {
            get {
                return ResourceManager.GetString("UnableToDeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kann Version nicht löschen!.
        /// </summary>
        internal static string UnableToRemoveVersion {
            get {
                return ResourceManager.GetString("UnableToRemoveVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kann Pfad nicht prüfen.
        /// </summary>
        internal static string UnableToValididatePath {
            get {
                return ResourceManager.GetString("UnableToValididatePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ein Update ist verfügbar! Willst du es jetzt installieren?.
        /// </summary>
        internal static string UpdateAvaliable {
            get {
                return ResourceManager.GetString("UpdateAvaliable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ein Update ist verfügbar! Willst du es jetzt installieren?.
        /// </summary>
        internal static string Updater_Avaliable {
            get {
                return ResourceManager.GetString("Updater_Avaliable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du hast die aktuellste Version. Willst du sie erneut runterladen?.
        /// </summary>
        internal static string Updater_UpToDate {
            get {
                return ResourceManager.GetString("Updater_UpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updater.
        /// </summary>
        internal static string UpdaterTitle {
            get {
                return ResourceManager.GetString("UpdaterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hochladen.
        /// </summary>
        internal static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nützliche Tasten im Spiel:
        ///
        ///Alt + Enter - Vollbild ein/aus
        ///F2 - Game Recording (Spielaufzeichnung) speichern
        ///Rechtsklick - A.I.R. Kontextmenü öffnen
        ///F3 - Game Controller Erkennung
        ///F4 - Game Controllers für Spieler 1 und 2 tauschen
        ///Numpad Plus/Minus - Globale Lautstärke anpassen
        ///Alt + B - Hintergrundunschärfe ändern
        ///Alt + F - Grafikfilter ändern
        ///Alt + P - Performance-Ausgabe.
        /// </summary>
        internal static string UsefulShortKeys {
            get {
                return ResourceManager.GetString("UsefulShortKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versionen.
        /// </summary>
        internal static string VersionsTab {
            get {
                return ResourceManager.GetString("VersionsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ja.
        /// </summary>
        internal static string Yes_Button {
            get {
                return ResourceManager.GetString("Yes_Button", resourceCulture);
            }
        }
    }
}
